title : Simple-Notion
name: 'Simple-Notion'
# description: 'Simple, light weight, responsive jekyll theme for hackers'
url: https://hwei-esay.github.io
baseurl: /Simple-Notion 

markdown: kramdown
highlighter: rouge
javascript_enabled: true

# featured_posts_title: Unrelated
# featured_posts:
#   - url: '#'
#     title: 'Featured post #1'
#   - url: '#'
#     title: 'Featured post #2'
#   - url: '#'
#     title: 'Featured post #3'

collections:
  Bulletins:
    title: Bulletins
    default_open: false
    output: true
  posts:
    title: Posts
    default_open: true
    output: true

defaults:
  - scope:
      type: posts
    values:
      title: Posts
      permalink: /post/:title
  - scope:
      type: posts
    values:
      title: Bulletins
      permalink: /bulletins/:title

plugins:
  - jekyll-sitemap
